name: axces-backend
# when we have multiple container, docker compose is used to manage them
# all containers are going to be the same network
services:
  mongo:
    image: mongo:latest
    container_name: axces-mongo
    ports:
      - "27017:27017"
    volumes:
      - axces_mongo_volume:/data/db

  backend:
    container_name: axces-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL = "mongodb://mongo:27017/"
      - PORT = 5000
      - JWT_SECRET = your_jwt_secret

      - CLOUDINARY_CLOUD_NAME = your_cloud_name
      - CLOUDINARY_API_KEY = your_api_key
      - CLOUDINARY_API_SECRET = your_api_secret

      - TWOFACTOR_API_KEY = your_api_key

      - RAZORPAY_KEY_ID = razorpay_key_id
      - RAZORPAY_KEY_SECRET = razorpay_key_secret
      - RAZORPAY_WEBHOOK_SECRET = razorpay_webhook_secret

volumes:
  axces_mongo_volume:
